"""
Telegram long-polling bridge for Adwi.

Delivery mode: getUpdates long polling — no public endpoint, no tunnel, no ngrok.
All traffic is outbound HTTPS from this Mac to api.telegram.org:443.

Safety model (applied in order on every inbound message):
  1. Sender allowlist  — only TELEGRAM_ALLOWED_USER_ID may issue commands.
     Unknown senders are silently dropped (no error message sent back).
  2. Command allowlist — TELEGRAM_COMMANDS maps Telegram /cmd → Safe Command API route.
     Anything not in the dict is rejected with a usage hint.
  3. Safe Command API  — localhost:5055 enforces its own allowlist + ADWI_LOCAL_SECRET.
     The Telegram bridge never bypasses or duplicates that gate.
  4. Confirmation gate — mutating commands (/repair_ok, /backup_ok) require a token
     generated by a preceding /repair_plan or /git_backup. Tokens expire in 5 minutes.
  5. Response cap      — replies truncated to REPLY_MAX_LEN chars before send.

What this bridge will never do:
  - Execute shell commands or run-bash/run-python
  - Accept input from anyone other than the configured user ID

Config (all from adwi/config/.env):
  TELEGRAM_BOT_TOKEN       — bot token from @BotFather
  TELEGRAM_ALLOWED_USER_ID — your numeric Telegram user ID (integer, not username)
  ADWI_LOCAL_SECRET        — shared secret for Safe Command API (:5055)

Usage:
  python3 adwi/services/telegram-bridge/bot.py
"""

from __future__ import annotations

import http.client
import importlib.util
import json
import logging
import os
import py_compile
import re
import secrets as _secrets_module
import subprocess
import time
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [telegram-bridge] %(levelname)s %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger(__name__)
log.setLevel(logging.INFO)  # explicit — basicConfig is no-op if root already has handlers (pytest)

HOME      = Path.home()
WORKSPACE = HOME / "SuneelWorkSpace"

VENV_PY      = str(WORKSPACE / "adwi" / ".venv" / "bin" / "python3")
ADWI_CLI     = str(WORKSPACE / "adwi" / "adwi_cli.py")
ADWI_BIN     = str(WORKSPACE / "adwi" / "bin")
ADWI_SCRIPTS = str(WORKSPACE / "adwi" / "scripts")

REPLY_MAX_LEN = 4000   # Telegram hard limit is 4096; headroom for ellipsis suffix
POLL_TIMEOUT  = 30     # seconds — getUpdates long-poll window
ADWI_API_HOST = "127.0.0.1"
ADWI_API_PORT = 5055
TG_API_BASE   = "https://api.telegram.org"

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*[A-Za-z]|\x1b\][^\x07]*\x07")
_CTRL_RE = re.compile(r'[\x00-\x1f\x7f]+')
_SECRET_RE = re.compile(
    r'(?i)(API_?KEY|SECRET|TOKEN|PASSWORD|ADWI_LOCAL)\s*=\s*\S+',
    re.IGNORECASE,
)
_TG_TOKEN_RE = re.compile(r'\b\d{8,12}:[A-Za-z0-9_-]{35}\b')
_MAX_ARG_LEN = 500

# ── Confirmation gate ─────────────────────────────────────────────────────────

_TOKEN_TTL  = 300   # seconds — 5 minutes
_PENDING: dict[str, dict] = {}   # token → {action, expires_at, meta}


def _make_token(action: str, meta: Optional[dict] = None) -> str:
    token = _secrets_module.token_hex(4)   # 8 hex chars
    _PENDING[token] = {
        "action":     action,
        "expires_at": time.time() + _TOKEN_TTL,
        "meta":       meta or {},
    }
    return token


def _consume_token(token: str) -> Optional[dict]:
    entry = _PENDING.pop(token, None)
    if entry is None or time.time() > entry["expires_at"]:
        return None
    return entry


def _expire_tokens() -> None:
    now     = time.time()
    expired = [t for t, e in list(_PENDING.items()) if now > e["expires_at"]]
    for t in expired:
        _PENDING.pop(t, None)


# ── Job runner (loaded from same directory) ───────────────────────────────────

def _load_job_runner():
    try:
        jr_path = Path(__file__).resolve().parent / "job_runner.py"
        spec    = importlib.util.spec_from_file_location("telegram_job_runner", jr_path)
        mod     = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
        spec.loader.exec_module(mod)                      # type: ignore[union-attr]
        return mod.JobRunner()
    except Exception as exc:
        log.warning("Job runner unavailable: %s", exc)
        return None


_JOB_RUNNER = _load_job_runner()


# ── Command allowlist ─────────────────────────────────────────────────────────
# Maps Telegram /command → Safe Command API route (or None for local handling).
# To add a Safe API command: the route must first exist in server.py ALLOWED_COMMANDS.
# Never add: run-bash, run-python, patch-adwi, self-heal, nightly-run,
#            git-commit, gmail-send/confirm, implement-idea, notify, file-write.

TELEGRAM_COMMANDS: dict[str, str | None] = {
    # ── Help & UX (local) ────────────────────────────────────────────────────
    "/help":              None,
    "/menu":              None,
    "/ping":              None,
    # ── Core status (Safe API) ───────────────────────────────────────────────
    "/status":            "/adwi-status",
    "/doctor":            "/adwi-doctor",
    "/services":          "/adwi-services",            # service port health
    "/obsidian":          "/adwi-obsidian-status",     # vault status
    # ── Observability (Safe API) ─────────────────────────────────────────────
    "/brief":             "/adwi-brief",
    "/daily-brief":       "/adwi-daily-brief-n8n",
    "/config":            "/adwi-config-check",
    "/disk":              "/adwi-disk-summary",
    "/eval-status":       "/adwi-eval-status",
    "/git-status":        "/git-status-workspace",
    "/git":               "/git-status-workspace",     # alias
    "/git_diff":          "/adwi-git-diff",
    "/git_log":           "/adwi-git-log",
    "/models":            "/adwi-models",
    "/nightly-status":    "/adwi-nightly-status",
    "/ports":             "/adwi-ports",
    "/uptime":            "/adwi-uptime",
    "/version":           "/adwi-version",
    "/watcher-status":    "/adwi-watcher-status",
    "/e2e-status":        "/adwi-e2e-auto-loop-status",
    # ── Test background jobs (local) ─────────────────────────────────────────
    "/test_quick":        None,
    "/test_nlu":          None,
    "/test_obsidian":     None,
    "/test_all":          None,
    "/tests_status":      None,
    # ── Learn & capture (local) ──────────────────────────────────────────────
    "/capture":           None,
    "/obsidian_review":   None,
    "/obsidian_plan":     None,
    "/obsidian_validate": None,
    "/memory_scan":       None,
    "/idea":              None,
    "/plan":              None,
    # ── Repair with confirmation gate (local) ────────────────────────────────
    "/repair_plan":       None,
    "/repair_ok":         None,
    # ── Git backup with confirmation gate (local) ─────────────────────────────
    "/git_backup":        None,
    "/backup_ok":         None,
    # ── Job management (local) ───────────────────────────────────────────────
    "/jobs":              None,
    "/job":               None,
    "/cancel":            None,
}

_HELP_LINES = [
    "Adwi Telegram Bridge — commands:",
    *[f"  {cmd:<20} → {route or 'local'}"
      for cmd, route in sorted(TELEGRAM_COMMANDS.items())],
    "",
    f"Total: {len(TELEGRAM_COMMANDS)} commands. Unknown commands are rejected.",
    "For grouped help: /menu",
]
HELP_TEXT = "\n".join(_HELP_LINES)

MENU_TEXT = f"""\
Adwi Remote Control — {len(TELEGRAM_COMMANDS)} commands

STATUS & HEALTH
  /status  /doctor  /services  /obsidian
  /ports   /uptime  /version   /eval-status
  /nightly-status   /disk      /models    /e2e-status

GIT (read-only)
  /git  /git-status  /git_diff  /git_log

TESTS (background — check with /tests_status)
  /test_quick   /test_nlu   /test_obsidian   /test_all
  /tests_status    /jobs    /job <id>    /cancel <id>

LEARN & CAPTURE
  /capture <type> <text>
    types: idea  decision  bug  fix  note  approval
  /idea <text>   /plan <text>
  /obsidian_review   /obsidian_plan   /obsidian_validate
  /memory_scan

REPAIR (confirmation required)
  /repair_plan  →  shows plan + token
  /repair_ok <token>

GIT BACKUP (confirmation required)
  /git_backup   →  shows plan + token
  /backup_ok <token>

INFO
  /brief  /daily-brief  /config  /watcher-status  /help  /ping"""


# ── Config loader ─────────────────────────────────────────────────────────────

def _load_env() -> None:
    """Load config/.env into os.environ (setdefault — does not override shell)."""
    env_path = WORKSPACE / "adwi" / "config" / ".env"
    if not env_path.exists():
        return
    for raw in env_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k = k.strip(); v = v.strip().strip('"').strip("'")
        if k and v:
            os.environ.setdefault(k, v)


# ── Text helpers ──────────────────────────────────────────────────────────────

def _strip_ansi(text: str) -> str:
    return _ANSI_RE.sub("", text)


def _redact(text: str) -> str:
    """Redact common secret patterns before sending via Telegram."""
    text = _TG_TOKEN_RE.sub("[TOKEN-REDACTED]", text)
    text = _SECRET_RE.sub(lambda m: m.group(0).split("=")[0] + "=[REDACTED]", text)
    return text


def _sanitize_text(text: str) -> str:
    """Remove control chars and truncate. Safe for use as a subprocess argv element."""
    return _CTRL_RE.sub(" ", text)[:_MAX_ARG_LEN].strip()


def _run_quick(argv: list[str], timeout: int = 30, cwd: Optional[str] = None) -> str:
    """Run a fast read-only command synchronously. Returns cleaned output string."""
    try:
        result = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=cwd or str(WORKSPACE),
            env={
                **os.environ,
                "PATH": (
                    f"{ADWI_BIN}:/opt/homebrew/bin"
                    ":/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
                ),
            },
        )
        out = result.stdout.strip()
        if result.returncode != 0 and result.stderr.strip():
            out += f"\n[exit {result.returncode}] {result.stderr.strip()[:200]}"
        return _strip_ansi(_redact(out)) or "(no output)"
    except subprocess.TimeoutExpired:
        return f"[timeout after {timeout}s]"
    except Exception as exc:
        return f"[error] {exc}"


# ── Telegram API helpers ──────────────────────────────────────────────────────

def _tg_url(token: str, method: str) -> str:
    return f"{TG_API_BASE}/bot{token}/{method}"


def _tg_post(token: str, method: str, payload: dict) -> dict:
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        _tg_url(token, method),
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=POLL_TIMEOUT + 10) as resp:
        return json.loads(resp.read())


def _tg_get_updates(token: str, offset: int) -> dict:
    url = _tg_url(token, "getUpdates") + f"?offset={offset}&timeout={POLL_TIMEOUT}"
    req = urllib.request.Request(url, method="GET")
    with urllib.request.urlopen(req, timeout=POLL_TIMEOUT + 10) as resp:
        return json.loads(resp.read())


def _send_reply(token: str, chat_id: int, text: str) -> None:
    if len(text) > REPLY_MAX_LEN:
        text = text[:REPLY_MAX_LEN] + "\n…[truncated]"
    try:
        _tg_post(token, "sendMessage", {"chat_id": chat_id, "text": text})
    except Exception as exc:
        log.error("sendMessage failed: %s", exc)


# ── Safe Command API caller ───────────────────────────────────────────────────

def _call_adwi(route: str, secret: str) -> str:
    """
    GET http://127.0.0.1:5055<route> with X-Adwi-Secret header.
    Returns plain-text output suitable for a Telegram reply.
    Never raises — errors surface as a bracketed string.
    """
    conn = http.client.HTTPConnection(ADWI_API_HOST, ADWI_API_PORT, timeout=120)
    try:
        conn.request("GET", route, headers={"X-Adwi-Secret": secret})
        resp = conn.getresponse()
        raw = resp.read().decode("utf-8", errors="replace")
        if resp.status != 200:
            return f"[error] HTTP {resp.status} from Adwi command API"
        data = json.loads(raw)
        stdout = data.get("stdout", "").strip()
        stderr = data.get("stderr", "").strip()
        rc     = data.get("returncode", 0)
        parts: list[str] = []
        if stdout:
            parts.append(stdout)
        if rc != 0 and stderr:
            parts.append(f"[exit {rc}] {stderr[:300]}")
        elif rc != 0:
            parts.append(f"[exit {rc}]")
        return _strip_ansi("\n".join(parts) if parts else "(no output)")
    except Exception as exc:
        return f"[error] {exc}"
    finally:
        conn.close()


# ── /daily-brief JSON formatter ──────────────────────────────────────────────

def _format_daily_brief(raw: str) -> str:
    """
    Parse the JSON emitted by /daily-brief --n8n and render as plain text.
    Falls back to raw text unchanged on any parse failure or unrecognized structure.
    """
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return raw

    if not isinstance(data, dict) or not data.get("ok"):
        return raw

    lines: list[str] = []

    ts = (data.get("generated_at") or "")[:16].replace("T", " ")
    lines.append(f"Daily Brief — {ts}" if ts else "Daily Brief")

    services = data.get("services")
    if isinstance(services, dict) and services:
        lines.append("Services: " + "  ".join(f"{k}={v}" for k, v in services.items()))

    gmail = data.get("gmail") or {}
    if isinstance(gmail, dict):
        g_warns = [w for w in (gmail.get("warnings") or []) if w]
        if g_warns:
            lines.append(f"Gmail: {'; '.join(g_warns)}")
        else:
            unread  = gmail.get("unread_count") or 0
            summary = (gmail.get("summary") or "").strip()
            if unread:
                lines.append(f"Gmail: {unread} unread today")
                if summary:
                    lines.append(summary)
            else:
                lines.append(f"Gmail: {summary or 'Inbox clear.'}")

    brief = (data.get("brief") or "").strip()
    if brief:
        lines.append("")
        lines.append(brief.replace("**", ""))

    warns = [w for w in (data.get("warnings") or []) if w]
    errs  = [e for e in (data.get("errors")   or []) if e]
    if warns:
        lines.append(f"Warnings: {'; '.join(warns)}")
    if errs:
        lines.append(f"Errors: {'; '.join(errs)}")

    return "\n".join(lines).strip()


# ── Local command handlers ────────────────────────────────────────────────────

_CAPTURE_TYPES = {"idea", "decision", "bug", "fix", "note", "approval"}

_TEST_JOBS: dict[str, tuple[str, list[str]]] = {
    "/test_quick": (
        "test-quick",
        [VENV_PY, "-m", "unittest",
         "adwi.tests.test_telegram_bridge",
         "adwi.tests.test_remote_control_surface",
         "--tb=short"],
    ),
    "/test_nlu": (
        "test-nlu",
        [VENV_PY, "-m", "unittest", "adwi.simlab.tests.test_nlu_regex", "--tb=short"],
    ),
    "/test_obsidian": (
        "test-obsidian",
        [VENV_PY, str(WORKSPACE / "adwi" / "scripts" / "validate_obsidian_vault.py")],
    ),
    "/test_all": (
        "test-all",
        [VENV_PY, "-m", "unittest", "discover", "-s", str(WORKSPACE / "adwi"),
         "-p", "test_*.py", "--tb=short"],
    ),
}


def _format_tests_status() -> str:
    """Show status of the most recent test job."""
    if _JOB_RUNNER is None:
        return "[error] Job runner not available."
    jobs = [j for j in _JOB_RUNNER.list_recent(20) if j.get("type", "").startswith("test-")]
    if not jobs:
        return "No test jobs run yet. Try /test_quick."
    j   = jobs[0]
    age = ""
    if j.get("end_time"):
        try:
            end = datetime.fromisoformat(j["end_time"])
            secs = (datetime.now() - end).total_seconds()
            age  = f" ({int(secs // 60)}m ago)"
        except Exception:
            pass
    lines = [
        f"Latest test: {j['type']}",
        f"  Status: {j['status']}{age}",
        f"  ID: {j['id']}",
    ]
    if j.get("status") in ("succeeded", "failed"):
        tail = _JOB_RUNNER.tail_log(j["id"], 12)
        if tail:
            lines.append("Last output:")
            lines.extend(f"  {l}" for l in tail.splitlines())
    lines.append(f"\nAll test jobs: /jobs  •  Full log: /job {j['id']}")
    return "\n".join(lines)


def _format_jobs_list() -> str:
    """List recent jobs."""
    if _JOB_RUNNER is None:
        return "[error] Job runner not available."
    jobs = _JOB_RUNNER.list_recent(10)
    if not jobs:
        return "No jobs yet."
    lines = ["Recent jobs (newest first):"]
    for j in jobs:
        start = (j.get("start_time") or "?")[:16]
        lines.append(f"  {j['status']:<10} {j['type']:<20} {start}  id={j['id']}")
    lines.append("\n/job <id> for details  •  /cancel <id> to cancel")
    return "\n".join(lines)


def _format_job_detail(job_id: str) -> str:
    """Show full job status + log tail."""
    if _JOB_RUNNER is None:
        return "[error] Job runner not available."
    if not job_id:
        return "Usage: /job <job-id>"
    j = _JOB_RUNNER.status(job_id)
    if not j:
        return f"Job not found: {job_id!r}"
    lines = [
        f"Job: {j['id']}",
        f"  Type:   {j.get('type', '?')}",
        f"  Status: {j.get('status', '?')}",
        f"  Start:  {(j.get('start_time') or '?')[:19]}",
        f"  End:    {(j.get('end_time') or '?')[:19]}",
        f"  Exit:   {j.get('returncode', '?')}",
    ]
    tail = _JOB_RUNNER.tail_log(job_id, 30)
    if tail:
        lines.append("\nLog (last 30 lines):")
        lines.extend(f"  {l}" for l in tail.splitlines())
    return "\n".join(lines)


def _do_cancel_job(job_id: str) -> str:
    if _JOB_RUNNER is None:
        return "[error] Job runner not available."
    if not job_id:
        return "Usage: /cancel <job-id>"
    ok = _JOB_RUNNER.cancel(job_id)
    return f"Cancelled: {job_id}" if ok else f"Could not cancel {job_id!r} — not running or not found."


def _do_capture(args: str, tg_token: str, chat_id: int) -> None:
    parts    = args.strip().split(maxsplit=1)
    if not parts:
        _send_reply(tg_token, chat_id,
                    f"Usage: /capture <type> <text>\n"
                    f"Types: {', '.join(sorted(_CAPTURE_TYPES))}")
        return
    cap_type = parts[0].lower()
    cap_text = parts[1].strip() if len(parts) > 1 else ""
    if cap_type not in _CAPTURE_TYPES:
        _send_reply(tg_token, chat_id,
                    f"Unknown type: {cap_type!r}\n"
                    f"Valid types: {', '.join(sorted(_CAPTURE_TYPES))}")
        return
    if not cap_text:
        _send_reply(tg_token, chat_id, f"Usage: /capture {cap_type} <text>")
        return
    cap_text = _sanitize_text(cap_text)
    result   = _run_quick([VENV_PY, ADWI_CLI, "/obsidian-capture", cap_type, cap_text], timeout=30)
    _send_reply(tg_token, chat_id, result or f"{cap_type.capitalize()} captured.")


def _do_repair_plan(tg_token: str, chat_id: int) -> None:
    # Quick syntax check
    syntax_ok = True
    try:
        py_compile.compile(ADWI_CLI, doraise=True)
    except py_compile.PyCompileError:
        syntax_ok = False

    # Git status summary
    try:
        gs_out = subprocess.run(
            ["git", "status", "--short"],
            capture_output=True, text=True, timeout=5, cwd=str(WORKSPACE),
        ).stdout.strip()
        dirty = len([l for l in gs_out.splitlines() if l.strip()])
    except Exception:
        gs_out = "(unknown)"
        dirty  = 0

    token_val = _make_token("repair", {})
    lines = [
        "Repair Plan",
        f"  adwi_cli.py syntax: {'✓ OK' if syntax_ok else '✗ FAIL'}",
        f"  Dirty files:        {dirty}",
        "",
        "Action: run adwi-self-heal (aider patching loop)",
        "This may modify source files. No git push.",
        "",
        f"Confirm: /repair_ok {token_val}",
        "Expires in 5 minutes.",
    ]
    _send_reply(tg_token, chat_id, "\n".join(lines))


def _do_repair_confirm(token_val: str, tg_token: str, chat_id: int) -> None:
    if not token_val:
        _send_reply(tg_token, chat_id, "Usage: /repair_ok <token>  (get token from /repair_plan)")
        return
    entry = _consume_token(token_val)
    if entry is None:
        _send_reply(tg_token, chat_id,
                    "Invalid or expired token. Run /repair_plan for a new one.")
        return
    if entry["action"] != "repair":
        _send_reply(tg_token, chat_id, "Token is for a different action.")
        return
    if _JOB_RUNNER is None:
        _send_reply(tg_token, chat_id, "[error] Job runner not available.")
        return
    heal_script = str(WORKSPACE / "adwi" / "bin" / "adwi-self-heal")
    job_id = _JOB_RUNNER.submit("repair", [heal_script])
    _send_reply(tg_token, chat_id,
                f"Repair job started.\nID: {job_id}\nCheck: /job {job_id}")


def _do_git_backup_plan(tg_token: str, chat_id: int) -> None:
    try:
        gs = subprocess.run(
            ["git", "status", "--short"],
            capture_output=True, text=True, timeout=5, cwd=str(WORKSPACE),
        ).stdout.strip()
        gl = subprocess.run(
            ["git", "log", "--oneline", "-1"],
            capture_output=True, text=True, timeout=5, cwd=str(WORKSPACE),
        ).stdout.strip()
    except Exception as exc:
        _send_reply(tg_token, chat_id, f"[error reading git state] {exc}")
        return

    dirty_lines = [l for l in gs.splitlines() if l.strip()]
    token_val   = _make_token("git_backup", {})
    lines = [
        "Git Backup Plan",
        f"  Last commit: {gl or '(none)'}",
        f"  Dirty files: {len(dirty_lines)}",
    ]
    for dl in dirty_lines[:8]:
        lines.append(f"    {dl}")
    if len(dirty_lines) > 8:
        lines.append(f"    … and {len(dirty_lines) - 8} more")
    lines += [
        "",
        "Action: adwi-git-backup (git add -A → commit → push)",
        "",
        f"Confirm: /backup_ok {token_val}",
        "Expires in 5 minutes.",
    ]
    _send_reply(tg_token, chat_id, "\n".join(lines))


def _do_backup_confirm(token_val: str, tg_token: str, chat_id: int) -> None:
    if not token_val:
        _send_reply(tg_token, chat_id, "Usage: /backup_ok <token>  (get token from /git_backup)")
        return
    entry = _consume_token(token_val)
    if entry is None:
        _send_reply(tg_token, chat_id, "Invalid or expired token. Run /git_backup for a new one.")
        return
    if entry["action"] != "git_backup":
        _send_reply(tg_token, chat_id, "Token is for a different action.")
        return
    if _JOB_RUNNER is None:
        _send_reply(tg_token, chat_id, "[error] Job runner not available.")
        return
    backup_script = str(WORKSPACE / "adwi" / "bin" / "adwi-git-backup")
    job_id = _JOB_RUNNER.submit("git-backup", [backup_script])
    _send_reply(tg_token, chat_id,
                f"Backup job started.\nID: {job_id}\nCheck: /job {job_id}")


# ── Main local command dispatcher ────────────────────────────────────────────

def _handle_local_cmd(
    cmd: str, args: str, tg_token: str, chat_id: int, secret: str
) -> None:
    """Dispatch locally-handled Telegram commands (background jobs, gates, UX)."""

    _expire_tokens()   # housekeeping on every local dispatch

    # ── Static / immediate ────────────────────────────────────────────────────

    if cmd == "/help":
        _send_reply(tg_token, chat_id, HELP_TEXT)
        return

    if cmd == "/menu":
        _send_reply(tg_token, chat_id, MENU_TEXT)
        return

    if cmd == "/ping":
        _send_reply(tg_token, chat_id, "Pong! Adwi Telegram bridge is alive.")
        return

    if cmd == "/tests_status":
        _send_reply(tg_token, chat_id, _format_tests_status())
        return

    if cmd == "/jobs":
        _send_reply(tg_token, chat_id, _format_jobs_list())
        return

    if cmd == "/job":
        _send_reply(tg_token, chat_id, _format_job_detail(args.strip()))
        return

    if cmd == "/cancel":
        _send_reply(tg_token, chat_id, _do_cancel_job(args.strip()))
        return

    # ── Test background jobs ──────────────────────────────────────────────────

    if cmd in _TEST_JOBS:
        if _JOB_RUNNER is None:
            _send_reply(tg_token, chat_id, "[error] Job runner not available.")
            return
        name, argv = _TEST_JOBS[cmd]
        job_id = _JOB_RUNNER.submit(name, argv)
        _send_reply(tg_token, chat_id,
                    f"Test job started.\nID: {job_id}\n"
                    f"Check: /job {job_id}  or  /tests_status")
        return

    # ── Learn & capture ───────────────────────────────────────────────────────

    if cmd == "/capture":
        _do_capture(args, tg_token, chat_id)
        return

    if cmd == "/idea":
        clean = _sanitize_text(args)
        if not clean:
            _send_reply(tg_token, chat_id, "Usage: /idea <description>")
            return
        result = _run_quick([VENV_PY, ADWI_CLI, "/obsidian-capture", "idea", clean])
        _send_reply(tg_token, chat_id, result or "Idea captured.")
        return

    if cmd == "/plan":
        clean = _sanitize_text(args)
        if not clean:
            _send_reply(tg_token, chat_id, "Usage: /plan <description>")
            return
        result = _run_quick([VENV_PY, ADWI_CLI, "/obsidian-capture", "note",
                              f"PLAN: {clean}"])
        _send_reply(tg_token, chat_id, result or "Plan captured.")
        return

    if cmd == "/obsidian_review":
        if _JOB_RUNNER is None:
            _send_reply(tg_token, chat_id, "[error] Job runner not available.")
            return
        days   = args.strip() or "7"
        job_id = _JOB_RUNNER.submit(
            "obsidian-review", [VENV_PY, ADWI_CLI, "/obsidian-review", days]
        )
        _send_reply(tg_token, chat_id,
                    f"Review job started.\nID: {job_id}\nCheck: /job {job_id}")
        return

    if cmd == "/obsidian_plan":
        if _JOB_RUNNER is None:
            _send_reply(tg_token, chat_id, "[error] Job runner not available.")
            return
        days   = args.strip() or "7"
        job_id = _JOB_RUNNER.submit(
            "obsidian-plan", [VENV_PY, ADWI_CLI, "/obsidian-plan", days]
        )
        _send_reply(tg_token, chat_id,
                    f"Plan job started.\nID: {job_id}\nCheck: /job {job_id}")
        return

    if cmd == "/obsidian_validate":
        if _JOB_RUNNER is None:
            _send_reply(tg_token, chat_id, "[error] Job runner not available.")
            return
        validator = str(WORKSPACE / "adwi" / "scripts" / "validate_obsidian_vault.py")
        job_id = _JOB_RUNNER.submit("obsidian-validate", [VENV_PY, validator])
        _send_reply(tg_token, chat_id,
                    f"Validate job started.\nID: {job_id}\nCheck: /job {job_id}")
        return

    if cmd == "/memory_scan":
        result = _run_quick([VENV_PY, ADWI_CLI, "/memory-recall", "recent"], timeout=30)
        _send_reply(tg_token, chat_id, result or "(no memory entries)")
        return

    # ── Repair with confirmation gate ─────────────────────────────────────────

    if cmd == "/repair_plan":
        _do_repair_plan(tg_token, chat_id)
        return

    if cmd == "/repair_ok":
        _do_repair_confirm(args.strip(), tg_token, chat_id)
        return

    # ── Git backup with confirmation gate ─────────────────────────────────────

    if cmd == "/git_backup":
        _do_git_backup_plan(tg_token, chat_id)
        return

    if cmd == "/backup_ok":
        _do_backup_confirm(args.strip(), tg_token, chat_id)
        return

    # Fallback — should not be reachable if TELEGRAM_COMMANDS is correct
    _send_reply(tg_token, chat_id, f"[internal] No local handler registered for {cmd!r}")


# ── Update handler ────────────────────────────────────────────────────────────

def _handle_update(update: dict, token: str, allowed_uid: int, secret: str) -> None:
    message = update.get("message") or update.get("edited_message")
    if not message:
        return

    sender = message.get("from")
    if not sender:
        return   # channel posts have no "from"

    chat_id   = message["chat"]["id"]
    sender_id = sender["id"]
    text      = (message.get("text") or "").strip()

    # 1. Sender allowlist — silent drop; do not reveal capability to unknown senders
    if sender_id != allowed_uid:
        log.warning("Dropped message from unknown sender_id=%s", sender_id)
        return

    if not text:
        return

    # Telegram appends @BotUsername to commands sent in groups — strip it
    cmd_token = text.split()[0].split("@")[0].lower()

    # 2. Command allowlist
    if cmd_token not in TELEGRAM_COMMANDS:
        n = len(TELEGRAM_COMMANDS)
        _send_reply(
            token, chat_id,
            f"Unknown command: {cmd_token!r}\n\n"
            f"Adwi has {n} commands. Send /help to see them all.",
        )
        return

    route = TELEGRAM_COMMANDS[cmd_token]

    # 3. Local handlers — no Safe API call
    if route is None:
        parts    = text.split(maxsplit=1)
        cmd_args = parts[1].strip() if len(parts) > 1 else ""
        _handle_local_cmd(cmd_token, cmd_args, token, chat_id, secret)
        return

    # 4. Dispatch via Safe Command API
    log.info("cmd=%s route=%s sender=%s", cmd_token, route, sender_id)
    _send_reply(token, chat_id, f"Running {cmd_token}…")
    result = _call_adwi(route, secret)
    if cmd_token == "/daily-brief":
        result = _format_daily_brief(result)
    _send_reply(token, chat_id, result or "(empty response)")


# ── Poll loop ─────────────────────────────────────────────────────────────────

def poll_loop(token: str, allowed_uid: int, secret: str) -> None:
    offset = 0
    log.info("Started. Long-polling Telegram (timeout=%ss per batch).", POLL_TIMEOUT)
    log.info("Allowed sender UID: %s", allowed_uid)
    while True:
        try:
            data = _tg_get_updates(token, offset)
            if not data.get("ok"):
                log.error("getUpdates error: %s", data)
                time.sleep(5)
                continue
            for update in data.get("result", []):
                uid = update["update_id"]
                try:
                    _handle_update(update, token, allowed_uid, secret)
                except Exception as exc:
                    log.error("Error handling update_id=%s: %s", uid, exc)
                offset = max(offset, uid + 1)
        except KeyboardInterrupt:
            log.info("Stopped by keyboard interrupt.")
            break
        except Exception as exc:
            log.error("Poll error: %s — retrying in 5s", exc)
            time.sleep(5)


# ── Entry point ───────────────────────────────────────────────────────────────

def _log_command_registry() -> None:
    """Log all registered commands and their destinations at startup."""
    local_count = sum(1 for r in TELEGRAM_COMMANDS.values() if r is None)
    api_count   = len(TELEGRAM_COMMANDS) - local_count
    log.info(
        "Command registry: %d total (%d via Safe API, %d local)",
        len(TELEGRAM_COMMANDS), api_count, local_count,
    )
    for cmd, route in sorted(TELEGRAM_COMMANDS.items()):
        dest = route if route else "local"
        log.info("  %-20s → %s", cmd, dest)


def main() -> None:
    _load_env()
    token   = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    uid_str = os.environ.get("TELEGRAM_ALLOWED_USER_ID", "")
    secret  = os.environ.get("ADWI_LOCAL_SECRET", "")

    if not token or token == "REPLACE_ME":
        print("[ERROR] TELEGRAM_BOT_TOKEN not set — add it to adwi/config/.env")
        raise SystemExit(1)
    if not uid_str or uid_str == "REPLACE_ME":
        print("[ERROR] TELEGRAM_ALLOWED_USER_ID not set — add it to adwi/config/.env")
        raise SystemExit(1)
    try:
        allowed_uid = int(uid_str)
    except ValueError:
        print(f"[ERROR] TELEGRAM_ALLOWED_USER_ID must be an integer, got: {uid_str!r}")
        raise SystemExit(1)
    if not secret:
        print("[WARNING] ADWI_LOCAL_SECRET not set — command API auth is disabled")

    if _JOB_RUNNER is None:
        log.warning("Job runner failed to load — background jobs will be unavailable.")

    _log_command_registry()
    poll_loop(token, allowed_uid, secret)


if __name__ == "__main__":
    main()
